// Weather actionTypes
export const FETCH_WEATHER = 'FETCH_WEATHER';

// API constants for fetching current weather
export const FETCH_CURRENT_WEATHER_PENDING = 'FETCH_CURRENT_WEATHER_PENDING';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';
export const FETCH_CURRENT_WEATHER_ABORTED = 'FETCH_CURRENT_WEATHER_ABORTED';

// API constants for fetching a 5 day forecast
export const FETCH_FORECAST_WEATHER_PENDING = 'FETCH_FORECAST_WEATHER_PENDING';
export const FETCH_FORECAST_WEATHER_SUCCESS = 'FETCH_FORECAST_WEATHER_SUCCESS';
export const FETCH_FORECAST_WEATHER_FAILED = 'FETCH_FORECAST_WEATHER_FAILED';
export const FETCH_FORECAST_WEATHER_ABORTED = 'FETCH_FORECAST_WEATHER_ABORTED';

// Still deciding if this is necessary
export const WEATHER_CLEAR = 'WEATHER_CLEAR';

//
export const CLEAR_STORED_CITIES = 'CLEAR_STORED_CITIES';

//
export const UPDATE_STORED_CITIES = 'UPDATE_STORED_CITIES';

// Input actionTypes
export const UPDATE_QUERY = 'UPDATE_QUERY';

